/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Icon: typeof import('@/components/icon/index.vue')['default']
    IconBranches: typeof import('@/components/icon/Branches.vue')['default']
    IconNotice: typeof import('@/components/icon/Notice.vue')['default']
    IconTabbarHome: typeof import('@/components/icon/tabbar/Home.vue')['default']
    IconTabbarHomeActive: typeof import('@/components/icon/tabbar/HomeActive.vue')['default']
    IconTabbarMine: typeof import('@/components/icon/tabbar/Mine.vue')['default']
    IconTabbarMineActive: typeof import('@/components/icon/tabbar/MineActive.vue')['default']
    IconTabbarStacking: typeof import('@/components/icon/tabbar/Stacking.vue')['default']
    IconTabbarStackingActive: typeof import('@/components/icon/tabbar/StackingActive.vue')['default']
    RichEditor: typeof import('@/components/rich/Editor.vue')['default']
    RichRead: typeof import('@/components/rich/Read.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('@/components/select/index.vue')['default']
    SelectColumn: typeof import('@/components/select/Column.vue')['default']
    VanArea: typeof import('vant/es')['Area']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSearch: typeof import('vant/es')['Search']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
