/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Icon: typeof import('@/components/icon/index.vue')['default']
    IconBranches: typeof import('@/components/icon/Branches.vue')['default']
    IconNotice: typeof import('@/components/icon/Notice.vue')['default']
    IconTabbarHome: typeof import('@/components/icon/tabbar/Home.vue')['default']
    IconTabbarHomeActive: typeof import('@/components/icon/tabbar/HomeActive.vue')['default']
    IconTabbarMine: typeof import('@/components/icon/tabbar/Mine.vue')['default']
    IconTabbarMineActive: typeof import('@/components/icon/tabbar/MineActive.vue')['default']
    IconTabbarStacking: typeof import('@/components/icon/tabbar/Stacking.vue')['default']
    IconTabbarStackingActive: typeof import('@/components/icon/tabbar/StackingActive.vue')['default']
    RichEditor: typeof import('@/components/rich/Editor.vue')['default']
    RichRead: typeof import('@/components/rich/Read.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('@/components/select/index.vue')['default']
    SelectColumn: typeof import('@/components/select/Column.vue')['default']
  }
}
